### ISSUE TITLE
Add example of how to setup a custom domain name

### ISSUE THREAD

**Issue by jgeschwendt** [jgeschwendt/serverless-prisma#7]
```yml
---
# DNS Setup
ApiGatewayBasePathMapping:
  DependsOn: ApiGatewayDomainName
  Type: AWS::ApiGateway::BasePathMapping
  Properties:
    BasePath: ''
    DomainName: ${env:DOMAIN_NAME}
    RestApiId:
      Ref: ApiGatewayRestApi # created by serverless, check the stack's resources
    Stage: dev

ApiGatewayCertificate:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: ${env:DOMAIN_NAME}

ApiGatewayDomainName:
  Type: AWS::ApiGateway::DomainName
  Properties:
    CertificateArn:
      Ref: ApiGatewayCertificate
    DomainName: ${env:DOMAIN_NAME}

ApiGatewayRecordSetGroup:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneName: ${env:HOSTED_ZONE_NAME}.
    Comment: DNS records associated with ${env:DOMAIN_NAME}
    RecordSets:
      - Name: ${env:DOMAIN_NAME}
        Type: A
        AliasTarget:
          DNSName: {'Fn::GetAtt': ApiGatewayDomainName.DistributionDomainName}
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: ${env:DOMAIN_NAME}
        Type: AAAA
        AliasTarget:
          DNSName: {'Fn::GetAtt': ApiGatewayDomainName.DistributionDomainName}
          HostedZoneId: Z2FDTNDATAQYW2
```
